### PR TITLE
Allow user selection of strings in tree

### PR DESCRIPTION
**Pull request by zertosh**
Mostly so you can copy+paste node types. cc: @fkling

### CODE REVIEW

**Comment by pieterv** [comment]
So happy about this! Nice work @zertosh

**Comment by fkling** [comment]
Nice! I disabled selection, because quickly clicking on the togglers would select the text otherwise, which is annoying. But enabling this for values makes absolutely sense.

How about adding

```css
cursor: text;
```

as well, so that its clear that this is selectable?

**Comment by zertosh** [comment]
Good idea! I rebased the change

**Comment by hzoo** [comment]
:+1:

**Comment by fkling** [comment]
Thanks so much!

**Comment by fkling** [comment]
Updated `gh-pages` branch (373dfbabc5dff033e1cbdd1850f683acb247a9c4).

**Pull request merged**
