### PR TITLE
Little style improvements in main menu

### PR DESCRIPTION
**Pull request by jdichev**
Hello, I use and enjoy astexplorer alot lately but there are two little styling things that distract me so I tried to fix them. I hope it's OK with you.

- Menu item does not change its width when children are shown when mouseover
- Submenu is wide at least as it's parent item

Best regards,
J

### CODE REVIEW

**Comment by hzoo** [comment]
Maybe add a screenshot of the changes?

**Comment by jdichev** [comment]
Sure. First .gif file shows the issue. The second .gif file describes the fix. I hope you're OK with it.
 
issue

issue-fixed

**Comment by RReverser** [comment]
Oh yes, I was willing to fix this too. Looks great!

**Comment by jdichev** [comment]
Thanks :)

**Comment by fkling** [comment]
Yep, looks good to me, thank you! I will merge and update everything tomorrow.

**Pull request merged**
